cmd_drivers/misc/mediatek/fmradio/dummy.o := /home/necoman51/linaro-4.9/bin/arm-eabi-gcc -Wp,-MD,drivers/misc/mediatek/fmradio/.dummy.o.d  -nostdinc -isystem /home/necoman51/linaro-4.9/bin/../lib/gcc/arm-eabi/4.9.4/include -I/home/necoman51/kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/necoman51/kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/necoman51/kernel/include/uapi -Iinclude/generated/uapi -include /home/necoman51/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -I/home/necoman51/kernel/drivers/misc/mediatek/mach/mt6735/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Werror=format -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -O2 -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fstack-protector -mabi=aapcs-linux -mno-thumb-interwork -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1400 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/necoman51/kernel/drivers/misc/mediatek/mach/mt6735/include -D MTK_WCN_REMOVE_KERNEL_MODULE -I/home/necoman51/kernel/drivers/misc/mediatek/mach/mt6735/include -DWMT_PLAT_ALPS=1 -DMT6627_FM -DMT6625_FM -Idrivers/misc/mediatek/fmradio/inc -Idrivers/misc/mediatek/fmradio/mt6627/inc -Idrivers/misc/mediatek/fmradio/../connectivity/conn_soc/common/include -Idrivers/misc/mediatek/fmradio/../connectivity/conn_soc/common/linux/include -Idrivers/misc/mediatek/fmradio/../connectivity/common_detect    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(dummy)"  -D"KBUILD_MODNAME=KBUILD_STR(dummy)" -c -o drivers/misc/mediatek/fmradio/dummy.o drivers/misc/mediatek/fmradio/dummy.c

source_drivers/misc/mediatek/fmradio/dummy.o := drivers/misc/mediatek/fmradio/dummy.c

deps_drivers/misc/mediatek/fmradio/dummy.o := \

drivers/misc/mediatek/fmradio/dummy.o: $(deps_drivers/misc/mediatek/fmradio/dummy.o)

$(deps_drivers/misc/mediatek/fmradio/dummy.o):
